### ISSUE TITLE
plt draws on previously created figure

### ISSUE THREAD

**Issue by tvcv901** [SubsTheTechnomancer/Codegolf-Submissions#1]
`matplotlib.pyplot` draws on previously created figure. When there are two or more folders for holes, the plots get messed up.

A simple fix is to add [`plt.clf()`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.clf.html) at the start of `drawGraph()` in [`pre-commit`](https://github.com/SubsTheTechnomancer/Codegolf-Submissions/blob/94554887c31803b8ce2e2ec4dd2f09a52fc3d676/hooks/pre-commit#L43)

**Comment by SubsTheTechnomancer** [comment]
Fixed this issue, however used `plt.close()` instead because `plt.clf()`  will throw errors (although will not break the readme)
